source_channel_index: 0
target_channel_index: 0
affine_transform_zyx:
- [1.0, 0.0, 0.0, 0.0]
- [0.0, 1.0, 0.0, 0.0]
- [0.0, 0.0, 1.0, 0.0]
- [0.0, 0.0, 0.0, 1.0]
source_shape_zyx: [8, 100, 100]
target_shape_zyx: [8, 512, 512]
